Feat/description/properties and article
untitled-dream/lubimovka pull request #24
Opened 2022-06-03 13:41 UTC by xonika9

Задача #14 
Решил разделить блок project на 2 отдельных, чтобы не лезть в чужие файлы стилей. Первый делает @PavlovAles, второй делаю я. В конце можно будет объединить.
У блока с видео получилось много медиазапросов, в которых меняется размер, чтобы не появлялся нижний скролл. Если есть вариант сделать видео резиновым, предлагайте.
!При мердже нужно будет раскоментить код в html.

2022-06-03 15:32 UTC, PavlovAles reviewed
уф, ревьюить сложнее, чем кодить)
есть предложения, есть некоторые несостыковки с макетом

предложений по айфрэйму нет, но заметил горизонтальный скролл начиная с 360px (или 345px при режиме мобилки)

2022-06-03 15:32 UTC, PavlovAles commented on blocks/description-block/__card-download/description-block__card-download.css
> +.description-block__card-download:hover {
прикольно! мне нравится)
но не до конца похоже на макет, стрелка палой жертвой темного бэкграунда.. 

когда думал, как это можно реализовать, пришел к варианту двух одинаковых блоков с инвертированными цветами, где один лежит поверх второго. при ховере этот верхний блок можно смещать транслэйтом в нужную сторону, и прятать оверфлоу: хидден родительского блока 

предлагаю сообразить нам один вариант этих ссылок/кнопок (см. комментарий в файле разметки)

2022-06-03 15:42 UTC, noi5enu1sanc3 commented on index.html
> +              <button class="description-block__card-watch" type="button">
> на разборе брифа Виктор Малий обмолвился на этом месте, что "стоит подумать, где делать ссылку, где делать кнопку..."
> возможно есть смысл переделывать "смотреть читку" на ссылку, а "скачать пьесу" оставлять кнопкой, но я затрудняюсь сказать в чем он

мне кажется, здесь в обоих случаях это именно ссылки по функционалу. с Виктором обсуждали это периодически на вебинарах, что элемент может выглядеть как угодно, можно визуально заверстать его как кнопку, но если функционально это ссылка, то семантически это будет тег а. в том числе с точки зрения доступности (которая accessibility) - на ссылку можно например кликнуть правой кнопкой и открыть в новой вкладке, а с кнопкой такого не сделаешь. ну и тд

2022-06-03 17:50 UTC, EpiphES commented on index.html
> +              <button class="description-block__card-watch" type="button">
Я за то, чтобы "смотреть читку" сделать ссылкой, а "скачать пьесу" оставить кнопкой

2022-06-03 17:54 UTC, EpiphES commented on blocks/description-block/__video/description-block__video.css
> +  width: 690px;
можно ширину и высоту задать в относительных единицах: 
  width: 48vw;
  max-width: 690px;
  height: 27vw;
  max-height: 389px;

2022-06-04 06:23 UTC, xonika9 commented on index.html
> +      <div class="description-block description__properties">
Исправил

2022-06-04 06:27 UTC, xonika9 commented on index.html
> +        <div class="description-block__card">
Не совсем понял, о чем ты.
Решили, что карточка должна быть одна и та же, как в десктопе, так и в мобайл.
Единственный затык, иногда появляется левый бордер у кнопок 
![image](https://user-images.githubusercontent.com/65449058/171987456-52f94804-bf49-476d-b2a9-5a72b993aee7.png)

2022-06-04 06:28 UTC, xonika9 commented on blocks/description-block/__card-download/description-block__card-download.css
> +.description-block__card-download:hover {
Кнопка пока в режиме mvp.
Можешь свой вариант в коде изобразить?

2022-06-04 06:29 UTC, xonika9 commented on blocks/authors/__characters/authors__character.css
> +  margin: 20px 0 0;
В этом блоке подобрал отступы по ПП, но последние 2 строки переносятся некорректно из-за ширины блока. Ширина выставляется по слову "Ксения", а не по "Владимир". 
![image](https://user-images.githubusercontent.com/65449058/171987561-027403b3-3ef5-4285-89d8-a426871cebc6.png)

Если это критично, буду искать способ поднять Владимира.
Я хочу предложить сделать переносы вообще по-другому, чтобы имя и фамилия не были на разных строках с помощью неразрывного пробела. 
![image](https://user-images.githubusercontent.com/65449058/171987568-b3695fc4-3a00-430e-b801-74a6656a6a24.png)

2022-06-04 06:31 UTC, xonika9 commented
Ошибки поправил, написал кое-где комменты. Запрашиваю повторное ревью.

2022-06-04 06:35 UTC, xonika9 commented
Еще прошу обратить внимание, что мобильный макет 414px в ширину.
Сейчас скролл появляется на <363px, не могу понять из-за чего.

2022-06-04 07:53 UTC, PavlovAles commented on blocks/authors/__characters/authors__character.css
> +  margin: 20px 0 0;
думаю, что можно не заморачиваться с неразрывными пробелами
все-таки ФИО бывают разные и короткие и на десятки символов

2022-06-04 07:59 UTC, PavlovAles commented on index.html
> +        <div class="description-block__card">
![Снимок экрана 2022-06-04 в 10 56 03](https://user-images.githubusercontent.com/97961953/171990310-d45f0fbd-051a-47e4-85e6-33b9cb2dbf00.png)
отличается размер блока, расположение и начертание текста "Прочитать пьесу" (жирный шрифт), на макете ФИО в одну строку, и да не знаю в чем фишка, но левая граница кнопки

2022-06-04 08:02 UTC, PavlovAles commented on index.html
> +        <div class="description-block__card">
не поддерживаю вариант одинакового блока на разных разрешениях
если дезигнер решил, что блок должен быть другого размера, стоит ли с ним спорить? 
есть всякие разные эргономические принципы по которым строятся интерфейсы, тем более в части размеров элементов, и я бы лучше следовал требованиям

2022-06-04 08:04 UTC, xonika9 commented on index.html
> +        <div class="description-block__card">
Мы не о размерах, а о содержании. 
![image](https://user-images.githubusercontent.com/65449058/171990630-237963b3-2788-444d-bf1f-5f0a8dda6d5d.png)

2022-06-04 08:37 UTC, PavlovAles requested changes
с учетом предложения по стилям `description__properties` и доработок `description__card` под мобилку (что можно сделать и позже, ведь пока стараемся слепить десктопную версию)

2022-06-04 08:37 UTC, PavlovAles commented on blocks/description/__properties/description__properties.css
> +@media screen and (max-width: 1024px) {
предлагаю добавить свойства
```
    max-width: 602px;
    width: 100%;
```
где 602px - это ограничение, что указано для текста в блоке `description__article`
тогда ширина этих блоков выровняется, отступы будут одинаковые, глаз будет радоваться :)
а я в свою очередь продолжу этот концепт на верхние блоки с заголовками и аннотацией

2022-06-04 08:37 UTC, PavlovAles commented on index.html
> +        <div class="description-block__card">
да, про содержание не спорю, менять его точно не стоит, оставляем десктопный текст

2022-06-04 09:58 UTC, PavlovAles commented on blocks/description-block/__card-download/description-block__card-download.css
> +.description-block__card-download:hover {
понял, что мое предложение не рабочее))
зато нашел то, что надо в codepen
https://codepen.io/Lunoware/pen/JBPpev

2022-06-09 06:17 UTC, xonika9 commented
Запрашиваю повторное ревью.

2022-06-16 12:17 UTC, merged